### ISSUE TITLE
Live example error in Rich Grid with Declarative Markup

### ISSUE THREAD

**Issue by plemon** [ceolter/ag-grid#1353]
#### throws this exception: Uncaught TypeError: AgGridColumn.getChildColDefs is not a function
---
Stacktrace:
vendor-bundle.js:16084 : Uncaught TypeError: AgGridColumn.getChildColDefs is not a function
    at AgGridColumn.toColDef (https://ceolter.github.io/ag-grid-aurelia-example/scripts/app-bundle.js:23991:47)
    at https://ceolter.github.io/ag-grid-aurelia-example/scripts/app-bundle.js:1327:31
    at Array.map (native)
    at AgGridAurelia.initGrid (https://ceolter.github.io/ag-grid-aurelia-example/scripts/app-bundle.js:1326:18)
    at TaskQueue.flushTaskQueue (https://ceolter.github.io/ag-grid-aurelia-example/scripts/vendor-bundle.js:16143:16)
    at https://ceolter.github.io/ag-grid-aurelia-example/scripts/vendor-bundle.js:16112:22
    at handleFlushTimer (https://ceolter.github.io/ag-grid-aurelia-example/scripts/vendor-bundle.js:16070:9)

**Comment by plemon** [comment]
It is YOUR site not my code...hit F12 and take a look...

**Comment by ceolter** [comment]
sorry, i though you mean you had your own code that was similar to our online example.

i've checked the link, i see NO error in my console. i'm using chrome.

possible you have something cached?

either way, can you raise this in the Aurelia project? there is a team of us and it's Sean who looks at Aurelia and doesn't check the core ag-Grid issues.
