### ISSUE TITLE
Run-time errors after upgrading from 8.1.1 to 8.2.0

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1554]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After upgrading ag-grid and ag-grid-aurelia from v8.1.1 to v8.2.0, I see the errors below at run-time in the browser JavaScript console.

Although there is not a clear pointer to the ag-grid source code in the error output, I have verified this is caused by the ag-grid upgrade, because reverting back to the previously-installed 8.1.X version eliminates these errors.

The error is fatal, in that it looks like they are occurring during the dependency-resolution phase and they prevent loading/bootstrapping of the Aurelia application.

```
aurelia-bootstrap.19d3698….bundle.js:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (aurelia-bootstrap.19d3698….bundle.js:1)
    at Object.377 (app.f916a3c….bundle.js:1)
    at __webpack_require__ (aurelia-bootstrap.19d3698….bundle.js:1)
    at Object.<anonymous> (app.f916a3c….bundle.js:1)
    at Object.55 (app.f916a3c….bundle.js:1)
    at __webpack_require__ (aurelia-bootstrap.19d3698….bundle.js:1)
    at Object.main.ts (app.f916a3c….bundle.js:1)
    at __webpack_require__ (aurelia-bootstrap.19d3698….bundle.js:1)
    at Object.386 (app.f916a3c….bundle.js:1)
    at __webpack_require__ (aurelia-bootstrap.19d3698….bundle.js:1)
    at window.webpackJsonp (aurelia-bootstrap.19d3698….bundle.js:1)
    at app.f916a3c….bundle.js:1
__webpack_require__ @ aurelia-bootstrap.19d3698….bundle.js:1
377 @ app.f916a3c….bundle.js:1
__webpack_require__ @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ app.f916a3c….bundle.js:1
55 @ app.f916a3c….bundle.js:1
__webpack_require__ @ aurelia-bootstrap.19d3698….bundle.js:1
main.ts @ app.f916a3c….bundle.js:1
__webpack_require__ @ aurelia-bootstrap.19d3698….bundle.js:1
386 @ app.f916a3c….bundle.js:1
__webpack_require__ @ aurelia-bootstrap.19d3698….bundle.js:1
window.webpackJsonp @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ app.f916a3c….bundle.js:1
aurelia-bootstrap.19d3698….bundle.js:1 TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:197)
    at http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:10198
    at a (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:86927)
    at o._settlePromiseFromHandler (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:60319)
    at o._settlePromise (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:61122)
    at o._settlePromiseCtx (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:61630)
    at http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:16573
From previous event:
    at o.d [as _captureStackTrace] (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:24370)
    at o._then (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:55754)
    at o.then (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:54110)
    at a (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:98542)
    at Object.<anonymous> (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:99093)
    at Object.aurelia-bootstrapper-webpack (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:99099)
    at __webpack_require__ (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:198)
    at Object.382 (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:93520)
    at __webpack_require__ (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:198)
    at 140 (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:1841)
    at http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:1888
__webpack_require__.oe @ aurelia-bootstrap.19d3698….bundle.js:1
a @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromiseFromHandler @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromise @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromise0 @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromises @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
attributes (async)
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
attributes (async)
i @ aurelia-bootstrap.19d3698….bundle.js:1
a @ aurelia-bootstrap.19d3698….bundle.js:1
f.hasDevTools.i.settlePromises @ aurelia-bootstrap.19d3698….bundle.js:1
o._reject @ aurelia-bootstrap.19d3698….bundle.js:1
o._rejectCallback @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromiseFromHandler @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromise @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromiseCtx @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
attributes (async)
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
attributes (async)
i @ aurelia-bootstrap.19d3698….bundle.js:1
a @ aurelia-bootstrap.19d3698….bundle.js:1
f.hasDevTools.i.invoke @ aurelia-bootstrap.19d3698….bundle.js:1
o._then @ aurelia-bootstrap.19d3698….bundle.js:1
o.then @ aurelia-bootstrap.19d3698….bundle.js:1
t.then.n.modulesBeingLoaded.(anonymous function) @ aurelia-bootstrap.19d3698….bundle.js:1
n._execute @ aurelia-bootstrap.19d3698….bundle.js:1
o._resolveFromExecutor @ aurelia-bootstrap.19d3698….bundle.js:1
o @ aurelia-bootstrap.19d3698….bundle.js:1
e.WebpackLoader.a._import @ aurelia-bootstrap.19d3698….bundle.js:1
e.WebpackLoader.a.loadModule @ aurelia-bootstrap.19d3698….bundle.js:1
o @ aurelia-bootstrap.19d3698….bundle.js:1
i @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
a @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromiseFromHandler @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromise @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromise0 @ aurelia-bootstrap.19d3698….bundle.js:1
o._settlePromises @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
(anonymous) @ aurelia-bootstrap.19d3698….bundle.js:1
aurelia-bootstrap.19d3698….bundle.js:1 Unhandled rejection TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:197)
    at http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:10198
    at a (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:86927)
    at o._settlePromiseFromHandler (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:60319)
    at o._settlePromise (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:61122)
    at o._settlePromiseCtx (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:61630)
    at http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:16573
From previous event:
    at o.d [as _captureStackTrace] (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:24370)
    at o._then (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:55754)
    at o.then (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:54110)
    at a (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:98542)
    at Object.<anonymous> (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:99093)
    at Object.aurelia-bootstrapper-webpack (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:99099)
    at __webpack_require__ (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:198)
    at Object.382 (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:93520)
    at __webpack_require__ (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:198)
    at 140 (http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:1841)
    at http://127.0.0.1:8080/aurelia-bootstrap.19d36980ce7968076885.bundle.js:1:1888
```

**Expected behavior**

The ag-grid components should not throw run-time errors, and should not interfere with loading of the application.

**Minimal reproduction of the problem with instructions**

Use any Aurelia skeleton application, include ag-grid, and compare behavior of v8.1.1 vs v8.2.0.

**What is the motivation / use case for changing the behavior?**
See above.

**Please tell us about your environment:**
Mac OS

* **ag-Grid version:** 8.1.1/8.2.0

* **Browser:**
All

* **Language:** TypeScript 2

**Comment by don-bluelinegrid** [comment]
More information:

This seems related to ```bluebird.js``` type versions.  The errors listed above also occur in ag-grid v8.1.1, after having upgraded my ```@types/bluebird``` npm package.

Here is the version listing of what I had tried:

```
Package                           Current  Wanted  Latest  Location
@types/bluebird                    3.0.37   3.5.2   3.5.2  blueline-grid-gridcommand
```

When I use ```@types/bluebird 3.0.37```, with ```ag-grid 8.1.1``` the application works fine.
When I use ```@types/bluebird 3.5.2```, with ```ag-grid 8.1.1``` the application does not load at run-time.

When I use either ```@types/bluebird 3.0.37``` or ```@types/bluebird 3.5.2``` with ```ag-grid 8.2.0``` the application does not load at run-time.


Thanks,
Don

**Comment by seanlandsman** [comment]
Issued moved to aurelia repo: https://github.com/ceolter/ag-grid-aurelia/issues/13
