### ISSUE TITLE
IE 11 Object.keys bug after 10.0 upgrade

### ISSUE THREAD

**Issue by rymk** [ceolter/ag-grid#1651]
**I'm submitting a ...** 
[x] bug report

**Current behavior**
We have implemented 2 custom floating filters following documentation on ag-grid.com. These filters have worked correctly, until today when we updated to v. 10.0.0 from 9.1.0.

Now, when we load our AngularJS page/ag-grid instances we get the following error in **IE11** and the grid never loads.
```
TypeError: Object.keys: argument is not an Object
   at e.iterateObject (http://localhost:62881/Scripts/ag-grid.min.js:44:1663)
   at e.mergeDeep (http://localhost:62881/Scripts/ag-grid.min.js:44:2226)
   at Anonymous function (http://localhost:62881/Scripts/ag-grid.min.js:44:2272)
   at e.iterateObject (http://localhost:62881/Scripts/ag-grid.min.js:44:1722)
   at e.mergeDeep (http://localhost:62881/Scripts/ag-grid.min.js:44:2226)
   at e.prototype.getParams (http://localhost:62881/Scripts/ag-grid.min.js:290:3411)
   at e.prototype.createAgGridComponent (http://localhost:62881/Scripts/ag-grid.min.js:290:3268)
   at e.prototype.newFloatingFilterComponent (http://localhost:62881/Scripts/ag-grid.min.js:290:4052)
   at e.prototype.newFloatingFilterWrapperComponent (http://localhost:62881/Scripts/ag-grid.min.js:290:4544)
   at t.prototype.createFloatingFilterWrapper (http://localhost:62881/Scripts/ag-grid.min.js:512:5674) <ui-view class="ng-scope">

```
This error only happens in IE. Per [StackOverflow](https://stackoverflow.com/questions/31917961/object-keys-behavior-in-chrome-and-ie-11#answer-31919087) this is an issue related to IE implementing the Object.keys method using old JS standards.

**Workaround:** Override browser's definition of Object.keys with
```
Object.keys = function(obj) {
    var keys = [];

    for (var i in obj) {
      if (obj.hasOwnProperty(i)) {
        keys.push(i);
      }
    }

    return keys;
  };
```

**Expected behavior**
The page should load in IE without requiring us to override Object.keys method.

**Minimal reproduction of the problem with instructions**
[Slimmed Example](https://embed.plnkr.co/uRcQir4TdlFjKZPvwDHO/)   The filter is a little buggy here, I pulled it out of a large ag-grid with a shared factory and seem to have caused the max value to not always work.

* **ag-Grid version:** 10.0.0

* **Browser:** Bug exists in IE; works correctly in Chrome.

* **Language:** AngularJS, JavaScript

Thanks!

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for this, we have just created the ticket AG-482 to fix this, we will update this thread as soon as the fix is available.

**Comment by makinggoodsoftware** [comment]
Hi after further consideration we have decided not to do this, since we could break other peoples code that relies on this behaviour to be buggy...

Since you should be able to use a polyfill or similar... we are not doing this in our end

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/keys
