### ISSUE TITLE
fails to render Immutable.List<Immutable.Record<IXyz>>

### ISSUE THREAD

**Issue by laurelnaiad** [ceolter/ag-grid#737]
I was happy to read

> Notice that the grid has it's properties marked as immutable. Hence for object properties, the object reference must change for the grid to take impact.  (from https://www.ag-grid.com/best-angular-2-data-grid/index.php) 

but I can't seem to make the grid work with an Immutable List of Records. ~~It clearly is able to iterate them~~ *(I think it at least checks the length)*, for the correct height is set (I have my styles set to follow the row heights), but when rendering it seems to choke. In this stack trace, `isUnread` is one of my row properties, but it seems like the entire object representing the row has gone missing.

(If I give it the `.toJS()` version of the same data structure, everything's fine)

```
"TypeError: Cannot read property 'isUnread' of undefined
    at eval (http://localhost:3000/app/feat/alerting/ui/alertsTable.js:40:93)
    at eval (http://localhost:3000/app/comp/od-ag-grid/odAgGrid.js:53:32)
    at VHtmlElement.VElement.fireElementAttached (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/virtualDom/vElement.js:26:13)
    at VHtmlElement.VElement.elementAttached (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/virtualDom/vElement.js:31:14)
    at VHtmlElement.elementAttached (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/virtualDom/vHtmlElement.js:190:38)
    at VHtmlElement.fireElementAttachedToChildren (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/virtualDom/vHtmlElement.js:203:13)
    at VHtmlElement.elementAttached (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/virtualDom/vHtmlElement.js:193:10)
    at RenderedRow.bindVirtualElement (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/rendering/renderedRow.js:187:14)
    at new RenderedRow (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/rendering/renderedRow.js:91:10)
    at RowRenderer.insertRow (http://localhost:3000/jspm_packages/npm/ag-grid@3.3.3/dist/lib/rendering/rowRenderer.js:257:23)"
```

**Comment by ceolter** [comment]
i can't see what's wrong, it is in your code that the 'isUnread' error is occurring. the grid verion you are using uses a virutal dom, and it's in the calllback 'elementAttached' (after the virtual dom is made real) is where the problem is been caused. in the next release, i have taken OUT the virtual dom, as it doesn't give any performance gains in most browsers. so you would try again when the next version is out, in case it's something to do with the virtual dom.

however i think not, and with the above, i can see anything wrong in ag-Grid. i'm going to close. we can reopen if you can narrow it down and isolate it to something wrong in the grid?

**Comment by laurelnaiad** [comment]
Here is a plunker demonstrating what's not working. http://plnkr.co/edit/OehIQ3?p=preview Would you please take a look?

('isUnread' is a field name in my data... not an error condition, by the way, but anyway, the plunker sums up my issue)

**Comment by laurelnaiad** [comment]
It does seem to be iterating over something, because I get the cellRenderer callbacks, but in them the params.data property is missing altogether.

**Comment by ceolter** [comment]
i had a look, nothing obviously wrong. however i coudln't debug through it as the ag-grid code was minified.

**Comment by ceolter** [comment]
if you unminify, and then try to debug through ag-grid code yourself, the code is very well laid out so you could find the problem yourself

**Comment by laurelnaiad** [comment]
Found it. https://github.com/ceolter/ag-grid/blob/51f4a52a43af4e049b545b7ff183d9d697eedbf2/src/ts/rowControllers/inMemoryRowController.ts#L554

```
           var nodes = [];
            if (rows) {
              for (var i = 0; i < rows.length; i++) {
                var node = {};
                // node.data = rows[i]
                // if .get is present, then it's not an array
                node.data = rows.get ? rows.get(i) : rows[i];
                nodes.push(node);
              }
```
