### ISSUE TITLE
Microsoft Edge autofill breaks grid filter focussing.

### ISSUE THREAD

**Issue by ollieyeahlong** [ceolter/ag-grid#9214]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

If reporting a bug make sure to state.

**Current behaviour.**
Setup a basic grid with a 'First Name' column with key 'first_name', and enable a basic text floating filter for the column. Run the app in Microsoft Edge and enter the same text in the floating filter until Edge saves the information to your 'wallet' for autofilling. Empty the floating filter and click on the box to get the Edge autofill menu to appear. Select the suggested text to auto-fill. The text is entered into the box however the box does not get focussed as it should, and an error is thrown in the console:

<img width="374" alt="image" src="https://github.com/user-attachments/assets/e7986171-b87d-4a9c-ac94-8978d57fedd5">
<img width="253" alt="image" src="https://github.com/user-attachments/assets/79a5552b-0df1-4542-b59f-05031b5f0501">

Uncaught TypeError: Cannot destructure property 'headerRowIndex' of 'this.focusService.getFocusedHeader(...)' as it is undefined.
    at HeaderFilterCellCtrl.shouldStopEventPropagation (main.esm.mjs:16893:13)
    at HTMLDivElement.keydown (main.esm.mjs:13644:28)
    at _ZoneDelegate.invokeTask (zone.js:398:33)
    at ZoneImpl.runTask (zone.js:158:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:479:34)
    at invokeTask (zone.js:1109:18)
    at globalCallback (zone.js:1140:29)
    at HTMLDivElement.globalZoneAwareCallback (zone.js:1173:16)

**Expected behaviour.**
The filter box should correctly be focussed on autofill.

**Please tell us about your environment:**

* **AG Grid version:** 32.2.2

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
