### ISSUE TITLE
angular 2 - Tree structure - file browser mode throwing exception error on foreach

### ISSUE THREAD

**Issue by neelsbr** [ceolter/ag-grid#963]
Hi
I am getting below error after update ag-grid to latest version 4.2.6. 
"TypeError: Cannot read property 'forEach' of null
    at e.recursivelyFilter (http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:477:792)
    at e.execute (http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:477:693)
    at e.doFilter (http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:501:5814)
    at e.refreshModel (http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:501:2078)
    at http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:26:1476
    at Array.forEach (native)
    at e.dispatchEvent (http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:26:1456)
    at e.setColumnDefs (http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:80:21082)
    at e.init (http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:80:6383)
    at http://localhost:3000/node_modules/ag-grid/dist/ag-grid.min.js:38:3022"
Upto ag-grid 4.2.5 it was working fine. Any one know the reason?

**Comment by ceolter** [comment]
nothing to do with angular 2 - just difference in ag-grid versions.

i've put a filter into my local 'tree example' and cannot reproduce the problem.

can you reproduce in an plunker?

**Comment by ceolter** [comment]
are you using getNodeChildDetails as in the example here:
https://www.ag-grid.com/javascript-grid-tree/index.php

**Comment by neelsbr** [comment]
I am using this https://www.ag-grid.com/example-file-browser/index.php

**Comment by neelsbr** [comment]
yes, I am using getNodeChildDetails

**Comment by ceolter** [comment]
i've also just updated the file browser locally and it's workign with filtering

can you provide a plunker?

otherwise, without able to reproduce, i can't help fix

**Comment by neelsbr** [comment]
Hi 
Thanks for your reply. I have tried in plunker. Its works fine in this URL http://plnkr.co/XC7pn5W7NAj3gMJcxRnH . This one using angular2 beta 17. But I am using **angualr2 rc.1** . Can you please try in that?

**Comment by ceolter** [comment]
plunker doesn't work :(

![image](https://cloud.githubusercontent.com/assets/6539563/16036322/43376fca-3213-11e6-9d16-afb267c17e08.png)
